mindsphere/mindconnect-nodejs

.gitignore
.npmignore
Jenkinsfile
README.md
package-lock.json
package.json
test/mindconnect-agent-3.spec.ts
test/mindconnect-setup.spec.ts

chore: added CI/CD , cleaned up README.md, added badges

chore: added CI/CD , cleaned up README.md, added badges 

---

src/api/agent-auth.ts
src/api/credential-auth.ts
src/api/mindconnect-base.ts
test/mindconnect-agent-3-rsa.spec.ts
test/mindconnect-agent-3.spec.ts
test/mindconnect-setup.spec.ts

fix (auth): certificate checks 

---

package-lock.json
package.json
src/cli/commands/mc-agent-token.ts
src/cli/mc.ts

feat: agent-token command 

---

CHANGELOG.md
Jenkinsfile
package-lock.json
package.json
src/cli/commands/mc-agent-token.ts
src/cli/commands/mc-service-token.ts
src/cli/mc.ts

feat: service-token command

---

.gitignore
.npmignore
CHANGELOG.md
CONTRIBUTING.md
README.md
docs.yml
package-lock.json
package.json
src/cli/commands/command-utils.ts
src/cli/commands/mc-agent-status.ts
src/cli/commands/mc-service-token.ts
src/cli/commands/mc-starter-js.ts
src/cli/commands/mc-starter-ts.ts
src/cli/commands/mc-upload-timeseries.ts
src/cli/commands/mc-version-help.ts
test/mindconnect-utils.spec.ts

Closes #20 
Fixed in alpha version from:: 3.5.0-3

chore: improve examples and error message on csv upload

---

CHANGELOG.md
src/api/mindconnect-base.ts
src/cli/commands/iot-bulk-run.ts
src/cli/commands/mc-create-event.ts
src/cli/commands/mc-version-help.ts

- fixed incorrect handling of --force parameter in mc run-bulk command

fix(cli): --force handling

---

.npmignore
CHANGELOG.md
Jenkinsfile
package-lock.json
package.json
src/api/mindconnect-base.ts
src/cli/commands/mc-version-help.ts

from manual to automatic build

feat:license-checker

---

CHANGELOG.md
package-lock.json
package.json
src/api/sdk/iotfile/iot-file.ts
src/cli/commands/command-utils.ts
src/cli/commands/mc-create-event.ts
src/cli/commands/mc-list-files.ts
src/cli/commands/mc-onboard.ts
src/cli/commands/mc-upload-file.ts
src/cli/commands/mc-upload-timeseries.ts
src/cli/commands/mc-version-help.ts
src/cli/commands/spectrum-analysis.ts
src/cli/mc.ts

feat(cli): list-files command

---

CHANGELOG.md
package-lock.json
package.json
src/cli/commands/mc-list-assets.ts
src/cli/commands/mc-list-files.ts
src/cli/mc.ts

chore(prerelease): version 3.6.0-6 😸

---

CHANGELOG.md
package-lock.json
package.json
src/api/utils.ts
src/cli/commands/mc-agent-status.ts
src/cli/commands/mc-agent-token.ts
src/cli/commands/mc-onboard.ts
src/cli/commands/mc-upload-file.ts
src/cli/commands/mc-upload-timeseries.ts
test/mindconnect-agent-3.spec.ts

fix: CLI .mc directory location precedence

---

README.md

Added 
[![Forum](https://img.shields.io/badge/mindsphere-community-%23009999.svg)](https://community.plm.automation.siemens.com/t5/Developer-Space/bd-p/MindSphere-platform-forum)
badge

docs: added link to forum

---

.gitignore
.npmignore
CHANGELOG.md
README.md
package-lock.json
package.json
src/api/sdk/signal-validation/signal-validation-models.ts
src/api/sdk/signal-validation/signal-validation.ts
src/cli/commands/command-utils.ts
src/cli/commands/mc-version-help.ts
src/cli/commands/signal-validation.ts
src/cli/mc.ts
test/signal-validation-spec.ts

```bash
Usage: signal-validation|sv [options]
perform signal validation @
Options:
-f, --file <timeseries>                                              timeseries file (default: "timeseries-sample.json")
-o, --output <output>                                                result-file (signal-validation-mode.json)
-m, --mode [testdata|range|spike|jumps|noise|gaps|interpolate|bias]  mode see @ Additional Documentation
-n, --variablename [variablename]                                    this variable will be taken from timeseries (default: "variable1")
-l, --lowerlimit [lowerlimit]                                        processing lower limit (for range)
-u, --upperlimit [upperlimit]                                        processing upper limit (for range)
-w, --windowsize [windowsize] …
```

feat(cli): signal validation command

---

package-lock.json
package.json

chore: downgrade ora

---

CHANGELOG.md
package-lock.json
package.json
src/api/sdk/common/mindsphere-sdk.ts
src/api/sdk/index.ts
src/api/sdk/trend/trend-prediction-models.ts
src/api/sdk/trend/trend-prediction.ts
src/cli/commands/command-utils.ts
src/cli/commands/trend-prediction.ts
src/cli/mc.ts
test/trend-prediction-spec.ts

Trendprediction

---

CHANGELOG.md
package-lock.json
package.json
src/api/mindconnect-base.ts
src/cli/commands/mc-offboard-agent.ts
src/cli/commands/mc-version-help.ts

feat: better-offboard

---

package-lock.json
package.json
src/api/utils.ts
src/cli/commands/mc-service-credentials.ts

chore: fixed #155

---

CHANGELOG.md
package-lock.json
package.json
src/cli/commands/mc-proxy.ts
src/cli/commands/mc-version-help.ts
src/cli/mc.ts

feat: mc dev-proxy

---

CHANGELOG.md
package-lock.json
package.json
src/api/schema-template.ts
test/mindconnect-agent-3.spec.ts

feat: typed events

---

CHANGELOG.md
package-lock.json
package.json
src/api/agent-auth.ts
src/api/auth-base.ts
src/api/credential-auth.ts
src/api/mindconnect-agent.ts
src/api/mindconnect-base.ts
src/api/mqtt-opcua-auth.ts
src/api/sdk/common/credentials.ts
src/api/sdk/common/mindsphere-sdk.ts
src/api/sdk/common/sdk-client.ts
src/api/sdk/index.ts
src/cli/commands/mc-automap.ts
src/cli/commands/mc-create-agent.ts
src/cli/mc.ts
src/index.ts
test/credential-auth.spec.ts
test/mindconnect-agent-3-rsa.spec.ts
test/mindconnect-agent-3.spec.ts
test/mindconnect-agent-autoconfig.spec.ts
test/sdk-with-agent-auth.spec.ts
test/sdk-with-agent-auth.ts

feat: auto-mapping, sdk 

---

.vscode/launch.json
CHANGELOG.md
package-lock.json
package.json
src/api/mindconnect-agent.ts
src/api/mindconnect-base.ts
src/api/sdk/mcapi/mcapi.ts
src/cli/commands/html/sc/index.html
src/cli/commands/mc-version-help.ts
test/mindconnect-agent-autoconfig.spec.ts

feat: unique datapoints

---

CHANGELOG.md
package-lock.json
package.json
src/api/mindconnect-base.ts
src/cli/commands/command-utils.ts
src/cli/commands/html/sc/index.html
src/cli/commands/mc-version-help.ts

fix: frontend authentication

---

.gitignore
.npmignore
package-lock.json
package.json

Fixes #185 
Updated four files
1. package.json
2. package.lock.json
3. .gitignore
4. .npmignore

Update: added binary versions of the command line interface for windows, macos and linux

---

CHANGELOG.md
package-lock.json
package.json
src/api/mindconnect-base.ts
src/cli/commands/html/sc/index.html

- pkg assets
- docs: CHANGELOG
- 3.9.0-0

chore : updated changelog, updated version

---

src/cli/commands/create-asset.ts

feat: add the digital twin type option to create-asset command

---

CHANGELOG.md
package-lock.json
package.json
src/api/sdk/common/mindsphere-sdk.ts
src/api/sdk/data-lake/data-lake.models.ts
src/api/sdk/data-lake/data-lake.ts
src/api/sdk/index.ts
src/cli/commands/data-lake.ts
src/cli/commands/mc-proxy.ts
src/cli/mc.ts

feat: data-lake

---

CHANGELOG.md
CONTRIBUTING.md
Jenkinsfile
package-lock.json
package.json
src/cli/commands/html/sc/index.html
src/version.ts
test/agent-auth.spec.ts
test/agent-management.spec.ts
test/asset-management-aspecttypes.spec.ts
test/asset-management-assets.spec.ts
test/asset-management-assetypes.spec.ts
test/asset-management-files.spec.ts
test/credential-auth.spec.ts
test/diagnostic.spec.ts
test/event-analytics.spec.ts
test/identity-management.spec.ts
test/iot-file.spec.ts
test/iot-ts-aggregates.spec.ts
test/iot-ts-bulk-upload.spec.ts
test/kpi-calculation.spec.ts
test/mindconnect-agent-3-rsa.spec.ts
test/mindconnect-agent-3.spec.ts
test/mindconnect-agent-autoconfig.spec.ts
test/mindconnect-agent-performance-test.spec.ts
test/sdk-with-agent-auth.spec.ts
test/signal-validation.spec.ts
test/test-utils.ts
test/trend-prediction.spec.ts

chore: implemented passkey support in the environment variable for unit tests

---

CHANGELOG.md
CONTRIBUTING.md
Jenkinsfile
package-lock.json
package.json
test/agent-auth.spec.ts
test/agent-management.spec.ts
test/asset-management-aspecttypes.spec.ts
test/asset-management-assets.spec.ts
test/asset-management-assetypes.spec.ts
test/asset-management-files.spec.ts
test/credential-auth.spec.ts
test/identity-management.spec.ts
test/iot-file.spec.ts
test/iot-ts-aggregates.spec.ts
test/mindconnect-agent-3-rsa.spec.ts
test/mindconnect-storage.spec.ts
test/sdk-auth-test.spec.ts
test/signal-validation.spec.ts
test/tokenmanager-auth.spec.ts

chore: set of tests for s4f and sanity checks

---

src/api/sdk/kpi/kpi.ts

feat: add support for direct interaction to KPI Calculation Client

---

CHANGELOG.md
package-lock.json
package.json
src/api/mindconnect-models.ts
src/api/sdk/agent/agent-models.ts
src/api/sdk/mcapi/mcapi.ts
src/cli/commands/html/sc/index.html
src/version.ts

- Fix for the changed mapping behavior which now supports nullable strings [[#238](https://github.com/mindsphere/mindconnect-nodejs/issues/238)]

fix for the changed mapping behavior which now supports nullable strings

---

CHANGELOG.md
package-lock.json
package.json
src/api/sdk/common/mindsphere-sdk.ts
src/api/sdk/index.ts
src/api/sdk/tenant/tenant-management-models.ts
src/api/sdk/tenant/tenant-management.ts
src/cli/commands/subtenant.ts
src/cli/commands/tenant.ts
src/cli/mc.ts
test/tenant-management-test.ts

feat: tenant management

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/api/sdk/common/mindsphere-sdk.ts
src/api/sdk/index.ts
src/api/sdk/signal-calculation/signal-calculation-models.ts
src/api/sdk/signal-calculation/signal-calculation.ts
src/cli/commands/command-utils.ts
src/cli/commands/signal-calculation.ts
src/cli/mc.ts
test/signal-calculation.spec.ts

feat: signal calculation

---

CHANGELOG.md
src/cli/commands/data-lake.ts

feat: data lake event subscriptions

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/api/sdk/common/mindsphere-sdk.ts
src/api/sdk/index.ts
src/api/sdk/vfc/vfc-models.ts
src/api/sdk/vfc/vfc.ts
src/cli/commands/vfc.ts
src/cli/mc.ts
test/vfc.spec.ts

feat: vfc client
